### ISSUE TITLE
Doesn't work with Angular 7

### ISSUE THREAD

**Issue by Elanor-L** [TylerRick/angular-maphilight#8]
I tried to import the plugin in my project, I got a couple of errors about rxjs such as `rxjs/Subject has no exported member 'Subject'`.

I managed to make it work : I changed the two rxjs import statements (in angular-maphighlight.js and in maphighlight.component.d.ts : from` from 'rxjs/Subject'` to `from 'rxjs'`

Sorry @TylerRick, I don't have time to make a correction.

Elanor

**Comment by ricardomcardoso** [comment]
I updated the files you mentioned and the error was resolved. 
But now a new error is displayed when maphighlight is fired: window.jQuery(this.img).maphilight(this.configToApply());

> TypeError: window.jQuery(...).maphilight is not a function
> at MaphilightComponent.push../node_modules/ng-maphilight/angular-maphilight.js.MaphilightComponent.updateMaphilight (angular-maphilight.js:51)
>     at HTMLImageElement.img.onload [as __zone_symbol__ON_PROPERTYload] (angular-maphilight.js:38)
>     at HTMLImageElement.wrapFn (zone.js:1332)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Object.onInvokeTask (core.js:3811)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
>     at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
>     at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
>     at invokeTask (zone.js:1744)
>     at HTMLImageElement.globalZoneAwareCallback (zone.js:1770)

Can Someone help me, please?

**Comment by TylerRick** [comment]
I'm looking into getting it working with Angular 8...

@ricardomcardoso, did you happen to see #5 that (hopefully) addresses that error?

**Comment by TylerRick** [comment]
Okay I've released `ng-maphilight@1.0.1`, which is updated for Angular 8+ :tada: :smile: 

https://www.npmjs.com/package/ng-maphilight
